format="""
╭[](fg:#3b4252)\
$directory[](fg:#3b4252 bg:#aaaaaa)\
$git_branch$git_metrics$git_status$git_commit$git_state\
[](fg:#aaaaaa)$jobs $cmd_duration
╰$character$status$battery
"""

right_format="$python$nodejs$rust"
# 
# ╭$directory$git_branch$git_metrics$git_status$python$nodejs$rust$jobs$time
# Note rounded border chars found on https://www.aestheticsymbols.me/borders.html

# Inserts a blank line between shell prompts
add_newline = true

[character]                            # The name of the module we are configuring is "character"
vicmd_symbol = "[V](bold blue) "
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"

[python]
symbol = "[](green)"
style = "bold green"

[git_branch]
format = "[$symbol$branch]($style)"
symbol = " "
style = "fg:#222222 bg:#aaaaaa"

# [git_status]
# stashed = "[](blue)"
# ahead = "⇡${count}"
# diverged = "⇕⇡${ahead_count}⇣${behind_count}"
# behind = "⇣${count}"
# format = '([$all_status$ahead_behind]($style) )'


[directory]
truncation_length = 5
truncation_symbol = "…/"
home_symbol = ""
read_only_style = "fg:red bg:#3b4252"
read_only = "  "
style = "bg:#3b4252"
format = "[$path]($style)[$read_only]($read_only_style)[ ]($style)"


[git_status]
format = '[ $all_status$ahead_behind]($style)'
style = "bold bg:#aaaaaa"
conflicted = "[](red) "
up_to_date = "[](bold fg:#55ff55 bg:#aaaaaa) "
untracked = "[](bold fg:#ffbb00 bg:#aaaaaa) "
ahead = "⇡${count}(bold #ffbb00)"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "[⇣${count}](red)"
stashed = "[](bold fg:blue bg:#aaaaaa)"
modified = "[](bold fg:#f6f600 bg:#aaaaaa) "
staged = '[++\($count\) ](bold fg:#4444aa bg:#aaaaaa)'
renamed = "[襁](bold fg:blue bg:#aaaaaa)"
deleted = "[](bold fg:red bg:#aaaaaa) "

[jobs]
symbol = " 酪"
style = "bold fg:#ffbb00"
number_threshold = 1

[battery]
discharging_symbol="ﮊ"
[[battery.display]]
style = "bold red"
